# Generated by Django 5.1.2 on 2025-02-22 15:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesgv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LesgvHomePage",
            fields=[
                (
                    "fairemainhomepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lesgv.fairemainhomepage",
                    ),
                ),
                ("section1", wagtail.fields.RichTextField(blank=True, null=True)),
                ("section2", wagtail.fields.RichTextField(blank=True, null=True)),
                ("section3", wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("lesgv.fairemainhomepage",),
        ),
    ]
