# Generated by Django 5.1.2 on 2025-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesgv", "0002_lesgvhomepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fairemainhomepage",
            name="ghost_filter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fairemainhomepage",
            name="ghost_include",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fairemainhomepage",
            name="ghost_order",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fairemainhomepage",
            name="ghost_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fairemainpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("generique", "generique"), ("boule", "boule"), ("lesartsvoisins", "lesartsvoisins")],
                default="generique",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relatedagendaitemhomepage",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="wagtailsettings",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
