# Generated by Django 5.2.8 on 2025-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesgv", "0003_alter_fairemainhomepage_ghost_filter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fairemainpage",
            name="exclude_from_search",
            field=models.BooleanField(default=False),
        ),
    ]
