# Generated by Django 5.2.8 on 2025-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesgv", "0004_fairemainpage_exclude_from_search"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fairemainpage",
            name="exclude_from_search",
        ),
    ]
