# Generated by Django 5.1.2 on 2025-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="header_color_class",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Primary colors",
                        [("village-primary", "Couleur principale"), ("village-secondary", "Couleur secondaire")],
                    ),
                    ("Neutral colors", [("grey", "Grey")]),
                    (
                        "Illustration colors",
                        [
                            ("village-color3", "Couleur 3"),
                            ("village-color4", "Couleur 4"),
                            ("village-color5", "Couleur 5"),
                            ("village-color6", "Couleur 6"),
                            ("village-color7", "Couleur 7"),
                            ("village-color8", "Couleur 8"),
                            ("village-color9", "Couleur 9"),
                            ("village-color10", "Couleur 10"),
                            ("village-color11", "Couleur 11"),
                            ("village-color12", "Couleur 12"),
                            ("village-color13", "Couleur 13"),
                            ("village-color14", "Couleur 14"),
                            ("village-color15", "Couleur 15"),
                            ("village-color16", "Couleur 16"),
                            ("village-color17", "Couleur 17"),
                            ("village-color18", "Couleur 18"),
                            ("village-color19", "Couleur 19"),
                            ("village-color20", "Couleur 20"),
                        ],
                    ),
                ],
                help_text="Uses the French Design System colors",
                max_length=255,
                null=True,
                verbose_name="Background color",
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="header_cta_label",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Call to action label"),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="header_cta_text",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Call to action text"),
        ),
    ]
