# Generated by Django 5.2.8 on 2025-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village", "0002_alter_contentpage_header_color_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="exclude_from_search",
            field=models.BooleanField(default=False),
        ),
    ]
