# Generated by Django 5.2.8 on 2025-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village", "0003_contentpage_exclude_from_search"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="exclude_from_search",
        ),
    ]
