# Generated by Django 5.2.8 on 2025-11-19 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_village_blog", "0005_alter_directoryentrypage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="posts_per_page",
            field=models.PositiveSmallIntegerField(
                default=12,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Posts per page",
            ),
        ),
    ]
