# Generated by Django 5.2.8 on 2025-11-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdvoisins", "0001_initial"),
        ("wagtail_village_blog", "0006_alter_blogindexpage_posts_per_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="GDVoisinsAnnuairePage",
            fields=[
                (
                    "gdvoisinspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gdvoisins.gdvoisinspage",
                    ),
                ),
                (
                    "annuaire_page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtail_village_blog.directoryindexpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("gdvoisins.gdvoisinspage",),
        ),
    ]
