# Generated by Django 5.2.8 on 2025-11-21 07:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gdvoisins", "0002_gdvoisinsannuairepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gdvoisinspage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
